
package jd;

/**
 * CONTAINS ALL THE ENUMS USED IN THE PROJECT
 */
public enum PropertyType {
    
    SELECT_ICON,
    RESIZE_ICON,
    ADD_CLASS_ICON,
    ADD_INTERFACE_ICON,
    REMOVE_ICON,
    UNDO_ICON,
    REDO_ICON,
    ZOOM_IN_ICON,
    ZOOM_OUT_ICON,
    TO_CODE_ICON,
    SNAPSHOT_ICON,
    
    // TOOLTIPS
    SELECT_TOOLTIP,
    RESIZE_TOOLTIP,
    ADD_CLASS_TOOLTIP,
    ADD_INTERFACE_TOOLTIP,
    REMOVE_TOOLTIP,
    UNDO_TOOLTIP,
    REDO_TOOLTIP,
    ZOOM_IN_TOOLTIP,
    ZOOM_OUT_TOOLTIP,
    TO_CODE_TOOLTIP,
    SNAPSHOT_TOOLTIP
    
}
